print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "C:/Users/sharon/DOCUME~1/TESTIN~1/Assets/museum.ma"`)
{		
	file -o "C:/Users/sharon/DOCUME~1/TESTIN~1/Assets/museum.ma";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "C:/Users/sharon/DOCUME~1/TESTIN~1/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "C:/Users/sharon/DOCUME~1/TESTIN~1/Temp/CommandPipe";

$donepipeKill = `fopen "C:/Users/sharon/DOCUME~1/TESTIN~1/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
